# Site settings
title: C. Lin Code Blog
email: jerryclin@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello! Welcome to my code blog on my journey to become a web developer.
  As a former project manager, I also look forward to bridge the gap between management and development. 
  Cheers!
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://about.me/jerryclin # the base hostname & protocol for your site
github_username:  jerryclin

# Build settings
markdown: kramdown
